name: Build and Push Docker Image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set version
        id: get_version
        run: echo "::set-output name=version::$(echo $GITHUB_REF | cut -d / -f 3)"
      -
        name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: bboerst/prometheus-fpl-pushgateway:${{ steps.get_version.outputs.version }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            VCS_REF=${{ github.sha }}
            VERSION=${{ github.ref }}
